name: ${project.name}
main: com.github.maxopoly.MemeMana.MemeManaPlugin
author: Maxopoly
version: ${project.version}
depend: [CivModCore, BanStick, ExilePearl]
commands:
    manashow:
        permission: mememana.public
    manatransfer:
        permission: mememana.public
    manarefill:
        permission: mememana.public
    manareset:
        permission: mememana.admin
    manainspect:
        permission: mememana.admin
    managive:
        permission: mememana.admin
permissions:
    mememana.public:
        default: true
    mememana.admin:
        default: op
