name: ${project.name}
main: com.github.maxopoly.MemeMana.MemeManaPlugin
author: Maxopoly
version: ${project.version}
depend: [CivModCore, BanStick, ExilePearl]
commands:
    mana:
        permission: mememana.public
permissions:
    mememana.public:
        default: true
