name: ${project.name}
main: com.github.maxopoly.MemeMana.MemeManaPlugin
author: Maxopoly
version: ${project.version}
depend: [CivModCore, BanStick, ExilePearl]
commands:
    mana:
        permission: mememana.public
    manaadmin:
        permission: mememana.admin
permissions:
    mememana.public:
        default: true
    mememana.admin:
        default: op
